name: Generate Keystore
on:
  workflow_dispatch:  # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v \
            -keystore my-release-key.jks \
            -alias my-key-alias \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            -dname "CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown"
      - name: Base64 Encode
        run: base64 -w0 my-release-key.jks > keystore.base64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystore-base64
          path: keystore.base64
